POST http://127.0.0.1:5000/expenses
Content-Type: application/json

{
    "amount": 500,
    "category": "Food",
    "date": "22-08-2026"
}



###
GET http://127.0.0.1:5000/expenses
Content-Type: application/json


###
DELETE http://127.0.0.1:5000/expenses/999
Content-Type: application/json


###
PUT http://127.0.0.1:5000/expenses/2
Content-Type: application/json

{
    "amount": 1000,
    "category": "Travel",
    "date": "2026-08-23"
}


###
GET http://127.0.0.1:5000/expenses/2
Content-Type: application/json
