POST http://127.0.0.1:5000/expenses
Content-Type: application/json

{
    "amount": 1200,
    "category": "Travel",
    "date": "2026-08-24"
}


###
GET http://127.0.0.1:5000/expenses?min_amount=1000&max_amount=500
Content-Type: application/json


###
DELETE http://127.0.0.1:5000/expenses/3
Content-Type: application/json


###
PUT http://127.0.0.1:5000/expenses/2
Content-Type: application/json

{
    "amount": 1000,
    "category": "Travel",
    "date": "2026-08-23"
}


###
GET http://127.0.0.1:5000/expenses/2
Content-Type: application/json
