POST http://127.0.0.1:5000/expenses
Content-Type: application/json

{
    "amount": 1200,
    "category": "Travel",
    "date": "2026-08-24"
}


###
POST http://127.0.0.1:5000/budget
Content-Type: application/json

{
    "amount": 15000
}


###
POST http://127.0.0.1:5000/register
Content-Type: application/json

{
    "username": "ronak2",
    "password": "123456"
}


###
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
    "username": "ronak2",
    "password": "123457"
}

###
GET http://127.0.0.1:5000/expenses?min_amount=1000&max_amount=500
Content-Type: application/json


###
GET http://127.0.0.1:5000/expenses/statistics
Content-Type: application/json


###
GET http://127.0.0.1:5000/budget
Content-Type: application/json


###
GET http://127.0.0.1:5000/budget/alert
Content-Type: application/json


###
DELETE http://127.0.0.1:5000/expenses/3
Content-Type: application/json


###
PUT http://127.0.0.1:5000/expenses/2
Content-Type: application/json

{
    "amount": 1000,
    "category": "Travel",
    "date": "2026-08-23"
}


###
GET http://127.0.0.1:5000/expenses/2
Content-Type: application/json
